Rakesh9100/CalcDiverse

Calculators/Age-Calculator/Age-Calculator.js

Closes #39 
Modified Age-Calculator.js  to display the full date in DD-MM-YYYY format

Fixed: Full date can now be seen in age calculator

---

Calculators/Currency-Converter-Calculator/Currency-Converter-Calculator.js

Closes #31 
I have addeda small "if" statement which checks if the user input is valid or not, if it is not valid, then it prompts the user to correct the input
The updated code works on all screen sizes, moreover it works on all the datatypes

NaN handling in currency converter calculator

---

Calculators/GPA-Calculator/README.md
Calculators/GPA-Calculator/index.html
Calculators/GPA-Calculator/script.js
Calculators/GPA-Calculator/style.css
index.html

Closes #27 
Added GPA calculator.
Tested with dummy data.

GPA Calculator

---

assets/contact/contact.css
style.css

Closes #44 
I have added slight transition to all the buttons on the home page, moreover I have changed the cursor type to pointer when it is being hovered over any link
I have tested it on various different screen sizes and the website works flawlessly on all of them

Added transition to all the homepage buttons

---

Calculators/2D-Shapes-Calculator/2D-Shapes-Calculator.css
Calculators/2D-Shapes-Calculator/2D-Shapes-Calculator.html
Calculators/2D-Shapes-Calculator/2D-Shapes-Calculator.js

This Pull Request closes issue #57 
I have changed the style of the calculator using basic CSS and some modifications in the HTML code.
It has been checked for being responsive on all the devices on a Chrome browser.
Here is a video demonstration of the calculator:
[screen-capture (10).webm](https://github.com/Rakesh9100/CalcDiverse/assets/73214455/444b433c-5f1d-48ab-8043-a1a309dd5770)
More Screenshots

Enhanced designs of 2D Shape Calculator

---

.vscode/settings.json
Calculators/Length-Convertor/Length.css
Calculators/Length-Convertor/Length.html
Calculators/Length-Convertor/Length.js
Calculators/Length-Convertor/README.md
index.html

Closes #24 
I have added a Length Calculator, which converts the length between two specified units.
I have tested each unit and conducted manual conversions, and everything is functioning correctly.

Length Convertor Added

---

Calculators/Statistics-Calculator/README.md
Calculators/Statistics-Calculator/index.html
Calculators/Statistics-Calculator/script.js
Calculators/Statistics-Calculator/style.css
index.html

Closes #63 
Added a new statistics calculator that can take a dataset and calculate and show the statistics.
I tested with various dummy datasets.

Statistics Calculator

---

Calculators/3D-Shapes-Volume-Calculator/3D-Shapes-Volume-Calculator.html
Calculators/3D-Shapes-Volume-Calculator/3D-Shapes-Volume-Calculator.js

Added NaN handling component in the 3d-calculator.
Issue #19 
- Previously for any non-numeric input, the output used to be displayed as NaN, which is not a visually appealing output.
- Therefore, the code has been improvised to output "Enter numeric value" on non-numeric input
- This has been done with the help of regex(regular expressions) to allow only numeric value.
- Also for a better experience the text box which contains invalid input is marked by a red border.

Added nan-handler using regex

---

Calculators/Time-Calculator/README.md
Calculators/Time-Calculator/Time-Calculator.css
Calculators/Time-Calculator/Time-Calculator.html
Calculators/Time-Calculator/Time-Calculator.js
index.html

Calculates the Hours, Minutes and Seconds for any entered Time by the User.
- [] New feature (Adds a Calculator)
I have tested this on local machine, and it is working well without any Conflicts.
- [] I have added demonstration in the form of video file (attatched in #80 Issue)
Screenshots and recordings are provided in #80 Created Issue.

Added Time Calculator

---

Calculators/Grade-Calculator/README.md
Calculators/Grade-Calculator/grade.css
Calculators/Grade-Calculator/grade.html
Calculators/Grade-Calculator/grade.js
index.html

Closes #33
The user can enter as many subject marks as needed. The calculator will give the total points, points scored, percentage and grade.

Added subject grade calculator

---

index.html
script.js
style.css

Closes #67 
- Enlist all the contributors on the main website
- Showcase them into a hexagonal grid structure of all the contributors
- Or in honeycomb like structure
By merging this pull request 🧑‍💻

[SWOC'24] Contributor Section Added

---

Calculators/Factorial-Calculator/README.md
Calculators/Factorial-Calculator/index.html
Calculators/Factorial-Calculator/script.js
Calculators/Factorial-Calculator/style.css
index.html

Closes #77 
- Factorial calculator is ready.
- Responsive for small devices too.
- Glassmorphism effect of the card.
- Best designing of the background.

[SWOC'24] Factorial Calculator Project Ready

---

Calculators/Weight-Conversion/Weight-convertor.css
Calculators/Weight-Conversion/Weight-convertor.html
Calculators/Weight-Conversion/Weight-convertor.js
Calculators/Weight-Conversion/readme.md
index.html

Closes #17
Swiftly convert weight from kgs to pounds and vice-versa.

Weight Converter Calculator

---

Calculators/Percentage-Calculator/index.html
Calculators/Percentage-Calculator/script.js
Calculators/Percentage-Calculator/style.css
index.html

Closes #13 
It is a simple app where users can calculate percentage of any number
Just click on live server

Added percentage calculator

---

Calculators/Number-of-Days-Calculator/Number-of-Days-Calculator.css
Calculators/Number-of-Days-Calculator/Number-of-Days-Calculator.html

Closes #72
- Made background  subtle 
- Added uniformity in style 
- Enhanced overall style

Enhance UI of Days Calculator

---

style.css

**Closes #87** 
**Enhancement of  Navbar**
**# Description👨‍💻** 
This issue is to enhances the navbar and make it more responsive for the user.
-Good styling.
-Effective hover effects.
-Interactive color balance.
**The changes before and after can be seen below :** 
**The whole logo before :** 
**The whole logo after :** 
**The logo before :** 
**The logo after :** 
**The logo after on hovering :** 
**Nav Items before :** 
**Nav Items after :** 
**Nav Items after on hovering  :** 
**In detail, Navbar before :** …

Enhanced Navbar

---

assets/contact/contact.html
index.html

Closes #99 
Fixed the copyright year by automating it.
This has been tested by checking the website after making necessary changes.

[Fix] : Automated the Copyright year

---

Calculators/Bitwise-Calculator/Bitwise-Calculator.css
Calculators/Bitwise-Calculator/Bitwise-Calculator.html
Calculators/Bitwise-Calculator/Bitwise-Calculator.js
index.html

Added a Bitwise Operation Calculator.
Closes #114
Added a bitwise operation calculator to operate different binary inputs.
locally

Bitwise Calculator

---

Calculators/BMI-Calculator/BMI-Calculator.css
Calculators/BMI-Calculator/BMI-Calculator.html
Calculators/BMI-Calculator/BMI-Calculator.js
Calculators/BMI-Calculator/README.md

Closes #35 
Updated the UI and added Age feature

BMI Calculator UI Updated

---

Calculators/GPA-Calculator/index.html
Calculators/GPA-Calculator/style.css

Fixes Issue🛠️
Closes :[UI Changes in SGPA Calculator](https://github.com/Rakesh9100/CalcDiverse/issues/61#top)
#61
Description👨‍💻
In this pull request, I addressed the following changes to enhance the SGPA Calculator's user interface:
- Added space between the previous CGPA and previous credits for improved readability.
- Changed the background to a neomorphic design to enhance the overall visual appeal.
Type of change📄
Added Space between the Previous cgpa nd previous credits and changed background to neomorphism
Checklist✅
[] My code follows the style guidelines of this project
[] I have performed a self-review of my own code
[] I have commented my code, particularly in hard-to-understand areas
[] I have added demonstration in the form of GIF/video file
[] I am an Open Source …

SGPA Calculator UI Enhanced

---

index.html
script.js
style.css

Closes #137 
- Back to top button is ready for the website.
- Adding animation on hovering.
- Progress bar also added wrt to website page.

Scroll to Top Button Ready

---

.github/CONTRIBUTING_GUIDELINES.md

Closes #138 
- Added steps to contribution
- Added important guidelines
- Linked Code of Conduct, Licence
- Tips
- Designing done
- Study Material, etc.

Contributing Guidelines Readme Enhanced

---

Calculators/Simple-Intrest-Calculator/README.md
Calculators/Simple-Intrest-Calculator/index.html
Calculators/Simple-Intrest-Calculator/script.js
Calculators/Simple-Intrest-Calculator/style.css
index.html

Closes #46 
A user friendly simple interest calculator.
Feature update
locally

Added Simple Interest calculator

---

Calculators/Bill-Split-Calculator/README.md
Calculators/Bill-Split-Calculator/index.html
Calculators/Bill-Split-Calculator/script.js
Calculators/Bill-Split-Calculator/style.css
index.html

Closes #30 
Added bill split calculator.
Input total bill, number of people, get fair shares instantly.
by dummy data

Added Bill Split Calculator

---

Calculators/Square-Cube-Calculator/README.md
Calculators/Square-Cube-Calculator/index.html
Calculators/Square-Cube-Calculator/script.js
Calculators/Square-Cube-Calculator/style.css
index.html

Closes #164 
Added a calculator which calculates the square and cube of a number.
dummy data

Square and Cube calculator

---

index.html
style.css

Closes #135 
This PR fixes the content overflowing on mobile devices. The changes include:-
1. Removing Extra padding and margin around content inside the card (i.e. h1, button, and img).
2. Added buttons in a separate div to provide the flex property so that the nature of buttons remains the same throughout the website, maintaining the responsiveness and alignment in all devices.
3.  Removed PR conflicts
1. Fixed CSS file.
2. Added new elements to keep items aligned.
3.  PR merge conflicts removed
1. The issue has been tested multiple times by running the website through all types of devices available in Chrome Developer Tools.
2. Through testing has been done to ensure the responsiveness of the website all over.
Before 
After Fixing #135

Overflowing of card content on mobile screen

---

Calculators/Cubic-Equation-Calculator/README.md
Calculators/Cubic-Equation-Calculator/index.html
Calculators/Cubic-Equation-Calculator/script.js
Calculators/Cubic-Equation-Calculator/style.css
index.html

Closes #166 
Added a calculator that finds the roots of the cubic equation and displays them.
JS code reference : https://github.com/BaseMax/CubicEquationCalculator

Cubic Equation Calculator

---

Calculators/Simple-Interest-Calculator/index.html
Calculators/Simple-Interest-Calculator/style.css

Closes #193 
I reduced the overall size of the texts and divs which kept the originality of the website and also improved its visibility
I ran the website on multiple screen sizes and the website looked great in all of them

Fixed CSS issues in Simple Interest Calculator

---

Calculators/2D-Shapes-Calculator/2D-Shapes-Calculator.css
Calculators/2D-Shapes-Calculator/2D-Shapes-Calculator.html
Calculators/2D-Shapes-Calculator/2D-Shapes-Calculator.js

Closes  #185  Add more shapes to the 2d Calculators & Enhance UI.
**# Description👨‍💻** 
This issue adds more shapes to the present 2D Shape Calculator : 
- Adds more shapes
- Adds a new function if a negative value is entered.
- Asks different parameters for different shapes Eg: Circle, Rectangle, Rhombus.
- Enhances The whole UI of the Calculator.
**# Checklist✅** 
**# Screenshots/GIF📷**
The changes before and after making improvements can be seen in the below attached screenshots : 
**Before :** 
**After making …

Add more shapes to the 2d Calculators & Enhance UI

---

Calculators/Fuel-Efficiency-Calculator/index.html
Calculators/Fuel-Efficiency-Calculator/script.js
Calculators/Fuel-Efficiency-Calculator/style.css

Changed the Opacity and added clear button in Fuel Efficiency Calculator

---

Calculators/GCD-Calculator/README.md
Calculators/GCD-Calculator/index.html
Calculators/GCD-Calculator/script.js
Calculators/GCD-Calculator/style.css
index.html

fixes #155 
GCD Calculator calculates greatest common divisor of two values or multiple values
- ✅ Adds calculator

Added GCD Calculator

---

assets/contact/contact.css
style.css

Closes #227 
Changed nevbar position to sticky by changing some css.
I had Checked the changes by running website and found the issue is fixed 😊

Navbar made sticky

---

Calculators/Currency-Calculator/Currency-Calculator.css
Calculators/Currency-Calculator/Currency-Calculator.html
Calculators/Currency-Calculator/Currency-Calculator.js

Now it shows the countries details for which you are converting the currency , when you give amount and specify currency and convert it , it will display countries.
Closes #36 
- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have added demonstration in the form of GIF/video file
- [*] I am an Open Source Contributor

Added Country names to Currency Calculator

---

assets/Contributors/Contibutor.js
assets/Contributors/Contributor.html
assets/Contributors/style.css
index.html

Closes #172 
I have created a separate page for the contributors section, where contributor profile photo of github is present and also uses hover effect and added impressive heading

Enhance the Contributors Section

---

assets/contact/contact.html
index.html

Issue #252 
[Bug] : Contributers section of footer not working
Closes #252 
The problem is solved for home page as well as contact page.
Tested by me on website. Problem solved!

Footer links fixed

---

Calculators/Color-Code-Calculator/converter.js
Calculators/Color-Code-Calculator/index.html
Calculators/Color-Code-Calculator/readme.md
Calculators/Color-Code-Calculator/script.js
Calculators/Color-Code-Calculator/style.css
index.html

Closes #234 
Added a new calculator that calculates the desired color code of a color in a given format. It can inter-convert color codes between RGB, RGBA, Hexadecimal, HSL, HSV and CMYK
Tested on my local machine, after being hosted on localhost, looks and workd as intended.

Added Color Code calculator

---

Calculators/Differential-Calculator/script.js

Closes #261 
When user clicks on `Calculate Derivative` without entering any values in the input field or enters a series of spaces and tabs, but no real values, an alert pops up prompting the user to enter a mathematical function.
Tested on my local machine, looks and works as expected.

Handled NaN exception in Differential Calculator

---

Calculators/Age-Calculator/Age-Calculator.js

Closes #257
Provides an alert message to the user if they clicks on Calculate before entering any valid date/time 
Tested on my local machine, looks and works as intended !

Handled NaN exception in Age Calculator

---

Calculators/Statistics-Calculator/index.html
Calculators/Statistics-Calculator/script.js
Calculators/Statistics-Calculator/style.css

Closes #260 
- Alert shows when the textbox is empty, or alphabet are inputted for calculation.
- Enhanced UI of the calculator
Tested on my local machine.

UI enhancement and handled NaN values in Statistics calculator

---

Calculators/Heart-Rate-Calculator/README.md
Calculators/Heart-Rate-Calculator/index.html
Calculators/Heart-Rate-Calculator/script.js
Calculators/Heart-Rate-Calculator/styles.css
index.html

Closes #272 
Added Heart rate calculator

Added Heart Rate Calculator

---

Calculators/Matrix-Calculator/matrix.js

Allow Navigation Between Button Columns Using "Enter" Key
Closes #289 
Added ability to shift focus and navigate between different matrix columns, facilitating keyboard-friendly interaction.
https://github.com/Rakesh9100/CalcDiverse/assets/54339318/5ae890ff-8cc9-4b31-948c-818fcfc8e034

Added Enter Key navigation in Matrix Calculator

---

Calculators/Word-Count-Calculator/index.html
Calculators/Word-Count-Calculator/script.js
Calculators/Word-Count-Calculator/styles.css
index.html

Closes #291 
- Total Word Count: Include functionality to count and display the total number of words in the provided text.
- Unique Word Count: Implement a feature to count and display the number of unique words in the text.
- Average Word Length: Calculate and display the average length of words in the given text.
- Export Results: Allow users to export the calculated results in different formats (e.g., CSV, JSON) for further analysis or documentation.
Tested Completely in Local Environment

Word Count Calculator Added

---

Calculators/Word-Count-Calculator/README.md

Closes #304 
Added readme.md file for water intake calculator

Readme added in Word Count Calculator

---

Calculators/2D-Shapes-Calculator/2D-Shapes-Calculator.js
Calculators/Matrix-Calculator/matrix.js

Closes #305 
Displays a nice message to enter "valid numerical value" (alerts looks ugly yk)

Handle NaN in 2D Shapes Calculator

---

Calculators/Water-Intake-Calculator/script.js
Calculators/Water-Intake-Calculator/style.css

Closes #307 
Changed the user interface of Water Intake Calculator!!

UI Enhanced of Water Intake Calculator 

---

Calculators/Clothing-Size-Calculator/domManager.js
Calculators/Clothing-Size-Calculator/index.html
Calculators/Clothing-Size-Calculator/readme.md
Calculators/Clothing-Size-Calculator/script.js
Calculators/Clothing-Size-Calculator/size_mapping.json
Calculators/Clothing-Size-Calculator/styles.css
index.html

Closes #293
Added the International clothing size calculator
Tested on my local machine, looks and works as intended.

Added Clothing Size Calculator

---

Calculators/Basic-Calculator/index.html
Calculators/Basic-Calculator/script.js

Closes #258
Now user can use their keyboard to enter values, and also on pressing 'enter' the expression is evaluated.
Tested on my local machine, works and looks as intended
https://github.com/Rakesh9100/CalcDiverse/assets/86418216/d92bf357-123f-48c3-94e3-143e703f2226

Added Keyboard Input for User Values in Basic Calculator

---

Calculators/Trigonometric-Calculator/script.js

Closes #308 
Fixed #308 added the alert massage if user don't enter value or enter negative value.

Handled NaN in Trigonometric Calculator

---

Calculators/EMI-Calculator/index.html
Calculators/EMI-Calculator/readme.md
Calculators/EMI-Calculator/script.js
Calculators/EMI-Calculator/styles.css
index.html

Closes #14 
Given a loan amount, the interest rate (*per month*), and the tenure/duration of the loan, this calculator calculates the EMI to be paid per month by the individual.
Tested on my local machine, works and looks as intended.

Added EMI Calculator

---

Calculators/Taylor-Series-Calculator/index.html
Calculators/Taylor-Series-Calculator/readme.md
Calculators/Taylor-Series-Calculator/script.js
Calculators/Taylor-Series-Calculator/style.css
index.html

Closes #341 
A simple web-based calculator to compute the Taylor Series expansion of a mathematical function around a specified center point.

Added Taylor Series Calculator

---

Calculators/Baye's-Theorem-Calculator/README.md
Calculators/Baye's-Theorem-Calculator/index.html
Calculators/Baye's-Theorem-Calculator/script.js
Calculators/Baye's-Theorem-Calculator/styles.css
index.html

Closes #342 
he Bayesian Theorem Calculator is a web application designed to calculate the probability of an event A given that event B has occurred. Users can input the probability of A (P(A)), the probability of B given A (P(B|A)), and the probability of not A (P(~A)). The calculator then computes and displays the probability of A given B (P(A|B)).

Added Baye's Theorem Calculator

---

Calculators/Smith-Number-Calculator/README.md
Calculators/Smith-Number-Calculator/index.html
Calculators/Smith-Number-Calculator/script.js
Calculators/Smith-Number-Calculator/style.css
index.html

Closes #318 
The Smith Number Calculator is a web application designed to determine whether a given number is a Smith number or not.
A Smith number is a composite number whose sum of digits is equal to the sum of the digits of its prime factors, excluding the digit 1. In other words, a Smith number can be expressed as the product of its prime factors, and when you add up the digits of both the original number and its prime factors, the sums are the same.

Added Smith Number Calculator

---

Calculators/GST-Calculator/README.md
Calculators/GST-Calculator/index.html
Calculators/GST-Calculator/script.js
Calculators/GST-Calculator/style.css
index.html

Closes #324 
The GST (Goods and Services Tax) Calculator is a web application designed to calculate the GST amount and final price based on user-input amount and selected tax rate. Users can input the amount, choose a tax rate, and obtain details of the calculated GST amount and final price dynamically on the webpage.

Added GST Calculator

---

index.html
script.js
style.css

#287 Search Bar/Tab for searching calculator.
Closes #287 
Added **search bar** to search calculator.
This feature **filters** the **calculator** based on input.
For creating this I have used **HTML, CSS** and **JavaScript.**
I have taken care to **not disturb** the **original UI of website** and make it **responsive.**
This have been tested by me by running the website, no error found!!
https://github.com/Rakesh9100/CalcDiverse/assets/149922307/a04f8ecd-3b84-4e45-ae58-7f6aea1b213f

Added Search Bar for searching calculators

---

Calculators/Carbon-Footprint-Calculator/README.md
Calculators/Carbon-Footprint-Calculator/index.html
Calculators/Carbon-Footprint-Calculator/script.js
Calculators/Carbon-Footprint-Calculator/style.css
index.html

Closes #297 
This calculator estimates an individual's carbon footprint based on the miles driven per year, per month, and per week.

Added Carbon Footprint Calculator

---

index.html
style.css

Closes #383  
Made footer responsive by adding flexbox properties
Runs on all the mobile devices screen sizes

Made footer responsive

---

.vscode/settings.json
index.html
style.css

Closes #370 
I added logo in navbar section.

Added Logo in Navbar

---

Calculators/Power-Calculator/README.md
Calculators/Power-Calculator/index.html
Calculators/Power-Calculator/script.js
Calculators/Power-Calculator/styles.css
index.html

Closes #357 
A simple tool designed to help you convert power between different units.

Added Power Calculator

---

.vscode/settings.json
assets/contact/contact.css

#415  [Style] Enhancement of contact us page
Closes #415 
I had changed the font style and color of texts and changed CSS of Contact us page to match UI of website.
This has been tested by me by running the website, no error found.

Enhanced the contact page

---

Calculators/Net-Salary-Calculator/index.html
Calculators/Net-Salary-Calculator/style.css

Closes #435 
Updated the UI of the CTC (Net Salary Calculator) Calculator
Tested on my local machine, looks and works as intended.

Updated the UI of CTC calculator

---

Calculators/Environmental-Calculator/style.css

#455 Make Environmental calculator responsive.
Closes #455 
Added responsiveness to Environmental calculator.
For this I have done some changes in CSS.
This has been tested by me by running the website, no error found!!

Added responsiveness to Environmental calculator

---

assets/contact/contact.html
assets/contact/contact.js

Closes #366 
When a user enters numbers in Name field then it was getting accepted, but After form validation It only accepts the characters. If numbers are entered, An Alert is popped up saying Numbers are not allowed!
We ran this code on our editor & reviewed it twice, it's working fine.

Fixed Contact form name validation

---

assets/contact/contact.html
assets/contributors/contributor.html
index.html

closes  #476 
Twitter and facebook icons does not resemble the id of the person,fixed the issue by adding Id of the person.
Checked it by local deployment

Twitter Facebook links fixed in footer

---

Calculators/Rectangular-Polar-Calculator/index.html
Calculators/Rectangular-Polar-Calculator/style.css

Closes #384 
Fixed the Non-Responsiveness of the calculator on the smaller devices
Done testing by Developer tools. Tested on various screen sizes and optimize it for every screens.

Fixed the responsiveness of Rectangular Polar Calculator

---

assets/contact/contact.html
assets/contributors/contributor.html
assets/faq/faq.html
index.html

Closes #502 
Added Icons for the components present in the navbar.

Added icons to the navbar

---

Calculators/GPA-Calculator/style.css

Closes #471 
Made GPA calculator responsive

GPA calculator made responsive

---

style.css

Removed border radius from the navbar

---

index.html
style.css

Closes #608 
Earlier the search bar was not aligned in the center in the left pic as you can see!
I have fixed this bug to make it look better from the user's perspective(right pic)
Please refer to the screenshot attached!
Original (left) Vs Modified (Right)

Center aligned the Search Bar

---

Calculators/Website-Bandwidth-Calculator/README.md
Calculators/Website-Bandwidth-Calculator/index.html
Calculators/Website-Bandwidth-Calculator/script.js
Calculators/Website-Bandwidth-Calculator/style.css
index.html

Closes #555 
This is a simple website calculator that estimates the bandwidth needs of a website based on three factors:
Page Views, Average Page Size, Page Views Per Visitor (also known as redundancy factor).
- [] New feature (added new calculator)
Double checked the results from this calculator to a verified calculator that already exists on internet.

Added Website Bandwidth Calculator

---

Calculators/BMR-Calculator/README.md
Calculators/BMR-Calculator/index.html
Calculators/BMR-Calculator/main.js
Calculators/BMR-Calculator/script.js
Calculators/BMR-Calculator/style.css
index.html

Closes #653 
Added BMR calculator which will calculate basal metabolic rate of an individual with the help of height, weight and age.
I have run the calculator and tested its functionality.

Added Basal Metabolic Rate Calculator

---

Calculators/NPV-Calculator/README.md
Calculators/NPV-Calculator/index.html
Calculators/NPV-Calculator/script.js
Calculators/NPV-Calculator/style.css
index.html
package-lock.json

Closes #661 
Added a Net Present Value (NPV) calculator is a powerful financial tool designed to help users evaluate the profitability of an investment by calculating the present value of future cash flows.

Added Net Present Value Calculator

---

assets/about/about.html

Closes #640 
The links in the footer section in the About page have been fixed and they now re-direct to the correct links which were 
broken earlier. 
The links on About page fixed which were broken earlier and didn't redirect to the correct links associated.
https://github.com/Rakesh9100/CalcDiverse/assets/116306749/1a2cc7c5-1dfe-4509-9f3f-0048335c8a47

Fixed the footer broken links on About page

---

Calculators/Cricket-Calculator/index.html
Calculators/Cricket-Calculator/script.js

Closes #704 
Added the Net Run Rate Calculator which calculates the net run rate for a team by entering run scored, overs played, run conceded and overs bowled. 
I have checked by various test cases.

Added Net Run Rate (NRR) option in Cricket Calculator

---

Calculators/Systematic-Investment-Plan-Calculator/index.html
Calculators/Systematic-Investment-Plan-Calculator/script.js
Calculators/Systematic-Investment-Plan-Calculator/style.css

Closes #649 
This PR introduces a visually attractive SIP Calculator webpage that allows users to choose between two investment modes: SIP and Lump sum. The user can input the necessary parameters, and the calculator will compute the future value of the investment.
- Created a toggle mechanism to switch between SIP and Lump sum input fields.
- Implemented calculation logic for both SIP and Lump sum modes.
- Enhanced UI with CSS for a better user experience.
<br>

Enhanced and modified SIP Calculator

---

index.html

Closes #738 
Added animated icons in the footer links.
https://github.com/Rakesh9100/CalcDiverse/assets/137484958/ff200073-277c-47ae-ba9b-14adc26f5caa

Added icons in the footer links

---

README.md

Closes #783
I corrected a typo in the "Getting Started" section of the README.md file. The word "Perfom" was changed to "Perform." This update enhances the clarity and quality of the documentation.
I manually reviewed the README.md file to ensure the typo was corrected and verified that no other typographical errors were introduced.

Fixed the typo in readme

---

Calculators/Weather-Calculator/README.md
Calculators/Weather-Calculator/index.html
Calculators/Weather-Calculator/script.js
Calculators/Weather-Calculator/style.css
index.html

Closes #679 
The weather calculator calculates wind chill factor, dew point, heat index, and gives human thermal comfort. It also converts temperature by default in degree Fahrenheit.
Tested on different values of temperature, humidity and wind speed to ensure the accuracy of results.

Added Weather Calculator

---

Calculators/Basic-Calculator/index.html
Calculators/Basic-Calculator/script.js
Calculators/Basic-Calculator/style.css

Closes #633
Add border effect on inputs in Basic Calculator

Added hover effect on inputs in Basic Calculator

---

Calculators/Bitwise-Calculator/README.md
Calculators/Bitwise-Calculator/index.html
Calculators/Bitwise-Calculator/script.js

Closes #648 
In this PR, I fixed an issue in the bitwise calculator related to the NOT operation by updating the calculation formula. Additionally, I added two new bitwise operations: Left-Shift and Right-Shift.
The changes were tested using various input values to ensure correct functionality
Before :
After :

Added shift operations in Bitwise Calculator

---

Calculators/Circular-Prime-Calculator/README.md
Calculators/Circular-Prime-Calculator/index.html
Calculators/Circular-Prime-Calculator/script.js
Calculators/Circular-Prime-Calculator/style.css

Fixes #682 
* Changed the overall UI of the circular prime calculator by 
*  Improving animation effects on the title.
* Improving color aesthetics of the webpage.
* Enhancing the functioning of sections by adding a hovered translate effect.
* Improving the buttons.
* **Files changed**:
* index.html to add the necessary span tags for the title hover effect.
* script.js to add the span-hover effect to individual letters on the title.
* style.css to improve the overall UI.
Changes has been verified by hosting the index.html webpage.
https://github.com/Rakesh9100/CalcDiverse/assets/142206618/b8b7244e-424d-457f-a0f2-72e5b3753d7f

Enhanced Circular Prime Calculator UI

---

assets/contributors/contributor.css
assets/contributors/contributor.html
assets/contributors/contributor.js

Closes #755 
Scroll to top button added in Contributors page.

Added the scroll to top button in Contributors page

---

assets/contributors/contributor.css

Closes #778 
Align the contributors card horizontally.
Test on live server.

Fixed the alignment of contributor icon

---

style.css

Closes #780 
Fix the scroll to top button overlap for small devices
I ran for mobile, ipad ,desktop mode

Fixed the scroll to top button overlap for small devices

---

Calculators/Antilog-Calculator/index.html
Calculators/Antilog-Calculator/script.js
Calculators/Antilog-Calculator/style.css

Closes #861 
The base input while calculating the Antilog should be positive and not 1. This issue has been fixed by inculcating the necessary changes in index.html file in the input tag and using validateBaseInput function.
Also the number whose Antilog is being calculated should be positive which has been fixed on the similar lines by making changes in the input tag.
For more detailed information, review the changes made section.
The UI has also been improved.!
I've checked the code by running it on my system. Screenshot for the same has been attached.

Fixed negative inputs in Antilog Calculator

---

Calculators/Tip-Calculator/README.md
Calculators/Tip-Calculator/index.html
Calculators/Tip-Calculator/script.js
Calculators/Tip-Calculator/style.css
index.html

Closes #629 
Added the Tip calculator that calculates the tip amount and total amount on basis of Amount and tip percentage inputs.

Added Tip Calculator

---

style.css

Closes #745 
The color of the card has been enhanced. Previously, the color combination of the card made it difficult to read the text.
I experimented with various texts and font styles, which resulted in improved readability.

Enhanced the color of a card

---

README.md

Closes #716 
Included that the project comes under GSSoc'24 in the Readme file

Open Source Programs list updated

---

Calculators/Compound-Interest-Calculator/style.css

Closes #801 
fixed the mobile veiw

Made Compound Interest Calculator responsive

---

Calculators/Grade-Calculator/README.md
Calculators/Grade-Calculator/index.html
Calculators/Grade-Calculator/script.js
Calculators/Grade-Calculator/style.css

Closes #687 
The existing grade calculator is enhanced by providing the user the choice to calculate relative or absolute grade. The relative grade is calculated for a subject based on the class mean and standard deviation.
The feature has been tested for various edge cases.

Added relative grading option in Grade Calculator

---

assets/contact/contact.css
assets/contact/contact.html

Closes #718 
I redesign and update contact form css to look good and suit with theme.

Improved the text color in Contact form

---

Calculators/Nutrition-Calculator/README.md
Calculators/Nutrition-Calculator/index.html
Calculators/Nutrition-Calculator/script.js
Calculators/Nutrition-Calculator/style.css
index.html

Fixes Issue🛠️
Closes #835 
This PR introduces a new feature, the Nutrition Calculator, which allows users to calculate the nutritional value of their meals based on the ingredients they input. This feature enhances the user experience by providing valuable information about their dietary intake directly on the website.
Unit Tests: Developed unit tests for the core functions of the Nutrition Calculator to ensure accurate nutritional calculations.
Integration Tests: Conducted integration tests to ensure the Nutrition Calculator works seamlessly with existing website features.
Navigation Testing: Ensured that the new navigation link directs users correctly to the Nutrition Calculator page.
https://github.com/Rakesh9100/CalcDiverse/assets/123234572/988c3543-7ae7-44a7-8025-72c0b748783d

Added Nutrition Calculator

---

Calculators/2D-Distance-Calculator/index.html
Calculators/2D-Distance-Calculator/script.js
Calculators/Bill-Split-Calculator/style.css

Closes #764 
Added Reset Button in 2-D Distance Calculator.

Added reset button in 2D Distance Calculator

---

Calculators/Velocity-Acceleration-Calculator/README.md
Calculators/Velocity-Acceleration-Calculator/index.html
Calculators/Velocity-Acceleration-Calculator/script.js
Calculators/Velocity-Acceleration-Calculator/style.css
index.html

Added Velocity Acceleration Calculator

---

Calculators/Momentum-Calculator/README.md
Calculators/Momentum-Calculator/index.html
Calculators/Momentum-Calculator/script.js
Calculators/Momentum-Calculator/style.css
index.html

Closes #992 
It calculates momentum using mass and velocity and displays the result.
Performed tests by inputting several different values and also decimal values. The result is verified and successful.

Added Momentum Calculator

---

Calculators/Age-Calculator/index.html
Calculators/Age-Calculator/script.js

Closes #944 
Added a feature to generate a PDF document with the results of the age calculator. Extracted the age, months, weeks, days, hours, minutes, and seconds from HTML elements and added them to the PDF document. Also, added a button to trigger the generation of the PDF document.
I have tested the functionality by clicking the "Share Results" button and verifying that a PDF document is generated with the correct data.
Before
After
PDF

Added download result functionality to Age Calculator

---

Calculators/Weather-Calculator/style.css

Closes #1005 
made the weather calculator responsive
https://github.com/Rakesh9100/CalcDiverse/assets/124435030/7e31e5e6-3e3b-4757-9479-081fcf764dbe

Made Weather Calculator responsive

---

Calculators/Weight-Calculator/README.md
Calculators/Weight-Calculator/index.html
Calculators/Weight-Calculator/script.js
Calculators/Weight-Calculator/style.css
index.html

Closes #678 
In Weight Calculator, there are only two units available, I had added 8 more units.

Added more units in Weight Calculator

---

Calculators/Antilog-Calculator/index.html
Calculators/Antilog-Calculator/style.css

Closes #897 
**Improved :**
* Overall UI
* Responsiveness
* Color aesthetics
* Hover, animation effects.
**Changed Files :** 
* index.html
* style.css
Local hosted and checked the improvements.
https://github.com/Rakesh9100/CalcDiverse/assets/142206618/b80269be-571e-4900-9308-40e236446f94

Enhanced Antilog Calculator UI

---

.github/workflows/pr-merge-comment.yml

Closes #1143 
I updated the post method in the code .
I have  tested this on my local repository and it worked.

Fixed the auto comment on PR merge workflow

---

.github/workflows/autocomment-iss-close.yml
.github/workflows/issue-close-comment.yml

Fixes #846 
This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

Added auto commenting workflow when an issue is closed

---

script.js

Closes #1014 
Updated the code for search bar  to also match the description with title when we try to search.It will make easy for the user to easily find the explicit calculator for their use.

Improved the search result based on description

---

assets/about/about.html

Closes #917 
Fixed grammatical errors. Removed the long run on sentences, because they were making the about section hard to read. 
1. After fixing the errors, I opened the output on my machine to confirm that the changes were being reflected. 
Before: 
After:

Fixed grammar errors in the About Us section

---

Calculators/Real-Estate-Calculator/index.html
Calculators/Real-Estate-Calculator/script.js
Calculators/Real-Estate-Calculator/style.css

Closes #723 
I have added an option to select the currency of property value. 

Added rupees value in Real Estate Calculator

---

Calculators/Loan-Repayment-Date-Calculator/style.css

Closes #1146 
The UI of the Loan Repayment Calculator is enhanced and the visibility issue of the input is solved.
The UI looks much better

Enhanced Loan Repayment Date Calculator UI

---

script.js
style.css

Closes #875 
- Implemented for the search by the user for available calculators.
[Screencast from 2024-06-04 18-18-13.webm](https://github.com/Rakesh9100/CalcDiverse/assets/121082414/26c68f6b-408d-4c28-9676-aac6fd6190a9)

Implemented search result suggestion

---

Calculators/Freelance-Rate-Calculator/README.md
Calculators/Freelance-Rate-Calculator/index.html
Calculators/Freelance-Rate-Calculator/script.js
Calculators/Freelance-Rate-Calculator/style.css
index.html

Closes #1158 
The Freelance Rate Calculator is a tool that helps freelancers determine their optimal hourly or project-based rates based on various factors like desired annual income, billable hours per week, and vacation weeks per year.

Added Freelance Rate Calculator

---

Calculators/Eigenvalues-And-Eigenvectors-Calculator/README.md
Calculators/Eigenvalues-And-Eigenvectors-Calculator/index.html
Calculators/Eigenvalues-And-Eigenvectors-Calculator/script.js
Calculators/Eigenvalues-And-Eigenvectors-Calculator/style.css
index.html

Closes #1203 
The Eigenvalue and Eigenvector Calculator is a web-based tool designed to compute the eigenvalues and eigenvectors of a square matrix. This calculator supports matrices of varying sizes (from 2x2 up to 9x9) and is ideal for educational purposes, research, and various applications in mathematics and engineering.
**Features**
1. Dynamic Matrix Size Selection: Users can select matrix sizes from 2x2 to 9x9.
2. Interactive Matrix Input: Easy-to-use grid interface for matrix entry.
3. Real-Time Calculations: Computes eigenvalues and eigenvectors with the click of a button.
4. Responsive Design: Ensures compatibility across different devices and screen sizes.
https://github.com/Rakesh9100/CalcDiverse/assets/146121869/bf59d4a2-c98c-4f04-8cbc-7a043b4846ef

Added Eigenvalues And Eigenvectors Calculator

---

Calculators/Hookes-Law-Calculator/README.md
Calculators/Hookes-Law-Calculator/index.html
Calculators/Hookes-Law-Calculator/script.js
Calculators/Hookes-Law-Calculator/style.css
index.html

Closes #1254 
The Hooke's law calculator (spring force calculator) helps to determine the force in any spring that is stretched or compressed. One can also use it as a spring constant calculator if one knows the force. 3 fields are there spring displacement, spring force constant and Force(f) by entering any 2 inputs. The 3rd field is calculated.
F=−kΔx

Added Hookes Law Calculator

---

Calculators/Relative-Humidity-Calculator/README.md
Calculators/Relative-Humidity-Calculator/index.html
Calculators/Relative-Humidity-Calculator/script.js
Calculators/Relative-Humidity-Calculator/style.css
index.html

Closes #1248 
I have added `Relative-Humidity-Calculator`.

Added Relative Humidity Calculator

---

Calculators/BMR-Calculator/style.css

Closes #1217 
Made BMR Calculator responsive and fixed input box overflow

Made BMR Calculator responsive

---

Calculators/Bill-Split-Calculator/style.css

Closes #1027 
Made Bill Split Calculator responsive.

Made Bill Split Calculator responsive

---

Calculators/Trigonometric-Calculator/index.html
Calculators/Trigonometric-Calculator/style.css

Closes #1013 
Made Trigonometric Calculator responsive.

Made Trigonometric Calculator responsive

---

.vscode/settings.json
Calculators/Water-Intake-Calculator/README.md
Calculators/Water-Intake-Calculator/index.html
Calculators/Water-Intake-Calculator/script.js
Calculators/Water-Intake-Calculator/style.css

Closes #1115 
Added activity duration hours per day and temperature as parameters according to which the water intake calculator will now suggest a plan for water intake and determines the level of water dehydration.

Added more inputs in Water Intake Calculator

---

Calculators/Molarity-Calculator/README.md
Calculators/Molarity-Calculator/index.html
Calculators/Molarity-Calculator/script.js
Calculators/Molarity-Calculator/style.css
index.html

Closes #1340 
I have added the Molarity Calculator to the Project, Molarity calculator return mass: A tool to quickly calculate the mass of a compound needed to achieve a desired molarity in a solution.

Added Molarity Calculator

---

assets/faq/faq.js

Closes #1419 
Added the missing Open Source Program name in FAQ section.

Added the missing Open Source Program name

---

index.html
style.css

Closes #1043 
Added searching logo in Search Calculator box.

Added searching logo in Search Calculator box

---

Calculators/EBITDA-Calculator/README.md
Calculators/EBITDA-Calculator/index.html
Calculators/EBITDA-Calculator/script.js
Calculators/EBITDA-Calculator/style.css
index.html

Closes #1261 
EBITDA = Net Sales – Raw Material Costs – Employee Costs – Other Operating Expenses
This calculator helps businesses and financial analysts quickly compute the EBITDA and visualize the cost components using a doughnut chart. The calculator is designed to be responsive, displaying the form and chart side by side on larger screens and stacked vertically on smaller screens.

Added EBITDA Calculator

---

Calculators/Sleep-Cycle-Calculator/style.css

Closes #1345 
Worked on the responsiveness of the calculator.

Made Sleep Cycle Calculator responsive

---

README.md

Closes #973 
Added all the calculator names to the Readme document.
@Rakesh9100 I'm contributing under GSSoC 24. Label this PR under GSSoC 24 and label it as level three, as I have worked a lot to add more than 240 calculators to the README document.

Added all the calculator names to the Readme file

---

Calculators/2D-Shapes-Calculator/index.html
Calculators/2D-Shapes-Calculator/script.js

Closes #1134 
I have added metrics unit in 2D Shapes Calculator.

Added units in 2D Shapes Calculator

---

Calculators/Bitwise-Calculator/style.css

Closes #1131 
Made the contents responsive by the following changes:
- Reducing font size
- Decreasing margin and padding
- Increasing width of container.

Made Bitwise Calculator responsive

---

Calculators/Black-Hole-Number-Calculator/style.css

Closes #1136 
Adjusted the width of the header as well as the calculator container.

Made Black Hole Number Calculator responsive

---

Calculators/Definite-Integral-Calculator/style.css

Closes #1140 
Adjusted the width of the calculator container across different devices.

Made Definite Integral Calculator responsive

---

Calculators/Basic-Physics-Calculator/README.md
Calculators/Basic-Physics-Calculator/index.html
Calculators/Basic-Physics-Calculator/script.js
Calculators/Basic-Physics-Calculator/style.css
index.html

Closes #1081 
This pull request introduces the Basic Physics Calculator to enhance the CalcDiverse repository. This calculator includes functionalities to compute various basic physics quantities:
- Speed Calculation: Calculates speed given distance and time inputs.
- Acceleration Calculation: Computes acceleration based on initial and final velocities and time.
- Force Calculation: Determines force using mass and acceleration inputs.
- Pressure Calculation: Calculates pressure from area and force inputs.
- Work Calculation: Computes work based on force and distance inputs.
- Power Calculation: Determines power using energy and time inputs.
- Kinetic Energy Calculation: Computes kinetic energy using mass and velocity inputs.
Each calculator section is styled with a clean card interface …

Added Basic Physics Calculator

---

Calculators/Dream-Journal-Calculator/README.md
Calculators/Dream-Journal-Calculator/index.html
Calculators/Dream-Journal-Calculator/script.js
Calculators/Dream-Journal-Calculator/style.css
Calculators/Dream-Journal-Calculator/styles.css
index.html

Closes #1390 
The Dream Journal Calculator is an intuitive web application designed to help users record, analyze, and gain insights into their dreams. By leveraging advanced text analysis and visualization techniques, it offers a comprehensive look at the themes, emotions, and sentiments present in dream entries. This tool is perfect for anyone interested in understanding their dreams better and uncovering hidden patterns or recurring themes.
Features - 
1- Dream Entry Recording - Allows users to input a title, date, detailed description, and emotions associated with their dreams.
2- Word Cloud Generation - Creates a visual representation of the most frequently occurring words in the dream description, highlighting key themes.
3- Recurring Words Analysis - Identifies and lists words that …

Added Dream Journal Calculator

---

Calculators/GST-Calculator/README.md
Calculators/GST-Calculator/index.html
Calculators/GST-Calculator/script.js
Calculators/GST-Calculator/style.css

Closes #1453 
1. Added the quantity, add/remove GST feature.
2. Enhanced scrollbar thumb's UI.

Added more inputs in GST Calculator

---

Calculators/Event-Budget-Planner-Calculator/README.md
Calculators/Event-Budget-Planner-Calculator/index.html
Calculators/Event-Budget-Planner-Calculator/script.js
Calculators/Event-Budget-Planner-Calculator/style.css
index.html

Closes #1404 
Added Event Budget Planner Calculator with Two Price mode USD and INR.
Also add pie chart for showing cost break-down.
Gives correct advice for event according to budget.
This is also responsive for small screens.
It has background animations with colors.
It has title above form with animation of some scale.

Added Event Budget Planner Calculator

---

Calculators/Value-Added-Tax-Calculator/README.md
Calculators/Value-Added-Tax-Calculator/index.html
Calculators/Value-Added-Tax-Calculator/script.js
Calculators/Value-Added-Tax-Calculator/style.css
index.html

Closes #1359 
This pull request introduces the VAT Calculator to enhance the CalcDiverse repository. The calculator facilitates easy computation of Value Added Tax (VAT) related values for products or services:
- VAT Amount Calculation: Calculates the VAT amount based on the net price and VAT rate.
- VAT Inclusive Price Calculation: Computes the total price inclusive of VAT, given the net price and VAT rate.
Each calculator section features a modern card interface for input and output fields, ensuring intuitive user interaction and clarity of results. The design aligns seamlessly with the existing CalcDiverse website layout.
No additional dependencies are required for this change.

Added Value Added Tax Calculator

---

Calculators/Work-Calculator/README.md
Calculators/Work-Calculator/index.html
Calculators/Work-Calculator/script.js
Calculators/Work-Calculator/style.css
index.html

Closes: #1326 
I have added the calculator to calculate work.

Added Work Calculator

---

Calculators/Download-Time-Calculator/index.html
Calculators/Download-Time-Calculator/style.css

Closes #1145 
Modified HTML as well as CSS file in order to adjust the contents within the container across different screen sizes.

Made Download Time Calculator responsive

---

Calculators/Graphing-Calculator/README.md
Calculators/Graphing-Calculator/index.html
Calculators/Graphing-Calculator/script.js
Calculators/Graphing-Calculator/style.css

Closes #1468 
Added Graph for Expressions which includes x and y both.

Fixed Graphing Calculator not displaying graphs for many expressions

---

Calculators/Lorentz-Force-Calculator/README.md
Calculators/Lorentz-Force-Calculator/index.html
Calculators/Lorentz-Force-Calculator/script.js
Calculators/Lorentz-Force-Calculator/style.css
index.html

Closes #1432 
The Lorentz Force Calculator computes the force exerted on a charged particle moving through a magnetic field, allowing users to input magnetic field strength, charge, velocity, and angle. It provides a user-friendly interface with unit customization options and responsive design for seamless use on various devices.
@Rakesh9100, please check my changes and merge the changes to project to make contribution, sir.
Thank you

Added Lorentz Force Calculator

---

Calculators/Currency-Calculator/index.html
Calculators/Currency-Calculator/script.js

Closes #1456 
Added flags to their respective countries beside them when selected using javascript.

Added country flag beside country codes in Currency Calculator

---

assets/about/about.html
assets/contact/contact.html
assets/contributors/contributor.html
assets/faq/faq.html
index.html
script.js
style.css

Closes #1503 
When hovering over the navigation links (Home, About, Calculators etc.), the link color change, but the color reverts to white, making it indistinguishable from inactive links. Thus, made changes to highlight the current link.
https://github.com/Rakesh9100/CalcDiverse/assets/133188585/3999ac8e-444a-4e23-9dbe-f432ff992440

Highlighted the active menu item in navbar

---

Calculators/5-Band-Resistance-Calculator/index.html
Calculators/5-Band-Resistance-Calculator/style.css

Closes #1473 
Changes include :
* Fixed the necessity of scrolling in order to see the full viewport.
* Added hover effect and styles to the calculate button.
* Added hover effect and styles to the close button in popup.
https://github.com/Rakesh9100/CalcDiverse/assets/142206618/336eb55e-7e94-4fbf-95bd-7b2d6f3be9ae

Enhanced buttons in 5 Band Resistance Calculator

---

Calculators/Meal-Calorie-Calculator/README.md
Calculators/Meal-Calorie-Calculator/index.html
Calculators/Meal-Calorie-Calculator/script.js
Calculators/Meal-Calorie-Calculator/style.css
Calculators/Meal-Calorie-Calculator/styles.css
index.html

Closes #1518 
Added meal calorie calculator- if the food item is not presented in the database, I have added an option for custom input. Have shown in the attached video.
https://github.com/user-attachments/assets/4842ba97-643d-49cf-91cb-720bdb9821f2

Added Meal Calorie Calculator

---

Calculators/Isogram-Calculator/README.md
Calculators/Isogram-Calculator/index.html
Calculators/Isogram-Calculator/script.js
Calculators/Isogram-Calculator/style.css
index.html

Closes #1599 
I have added an Isogram calculator that calculates whether a string entered by the user is isogram or not.

Added Isogram Calculator

---

Calculators/Roots-Equation-Calculator/README.md
Calculators/Roots-Equation-Calculator/index.html
Calculators/Roots-Equation-Calculator/script.js
Calculators/Roots-Equation-Calculator/style.css
index.html

Closes #1072 
Add an equation generator calculator for given roots. First, it will ask for the number of roots and then the user has to enter the roots, after that, the equation would be generated.

Added Roots Equation Calculator

---

Calculators/FD-Calculator/README.md
Calculators/FD-Calculator/index.html
Calculators/FD-Calculator/script.js
Calculators/FD-Calculator/style.css
index.html

Closes #1579 
Added FD Calculator.
https://github.com/user-attachments/assets/7a66fc30-dda1-4874-8dcb-a0ce465108fc

Added FD Calculator

---

Calculators/Pace-Calculator/README.md
Calculators/Pace-Calculator/index.html
Calculators/Pace-Calculator/script.js
Calculators/Pace-Calculator/style.css
index.html

Closes #1689 
Added new calculator for athletes.

Added Pace Calculator

---

Calculators/PIN-Generator-Calculator/README.md
Calculators/PIN-Generator-Calculator/index.html
Calculators/PIN-Generator-Calculator/script.js
Calculators/PIN-Generator-Calculator/style.css
index.html

Closes #1317 
This PIN generator calculator produces random numeric sequences of specified length. Users can customize generated PINs by determining desired length and allowing or disallowing repeated digits.

Added PIN Generator Calculator

---

Calculators/3D-Distance-Calculator/style.css
Calculators/3D-Shapes-Calculator/style.css

Closes #1726 
Background do not have any styling changed, the background styling added with a working wave animation.

Improved the background in 3D Distance Calculator

---

Calculators/Cost-Of-Living-Calculator/README.md
Calculators/Cost-Of-Living-Calculator/Readme.md
Calculators/Cost-Of-Living-Calculator/index.html
Calculators/Cost-Of-Living-Calculator/script.js
Calculators/Cost-Of-Living-Calculator/style.css
Calculators/Cost-Of-Living-Calculator/styles.css
index.html

Closes #1682 
Added the cost of living calculator that compares the current salary in the current city with respect to another city

Added Cost Of Living Calculator

---

Calculators/Wedding-Budget-Calculator/README.md
Calculators/Wedding-Budget-Calculator/index.html
Calculators/Wedding-Budget-Calculator/script.js
Calculators/Wedding-Budget-Calculator/style.css
index.html

Closes #1160 
A simple web application to calculate the total budget of a wedding, including a breakdown of various costs like venue, catering, decor, photography, entertainment, attire, and other expenses.

Added Wedding Budget Calculator

---

style.css

Closes #1619 
I have added a hover effect to the Quick Links in the footer, which makes the links turn blue on hovering.

Added hover effect to the menu items in footer

---

Calculators/Harmonic-Progression-Calculator/README.md
Calculators/Harmonic-Progression-Calculator/index.html
Calculators/Harmonic-Progression-Calculator/script.js
Calculators/Harmonic-Progression-Calculator/style.css
index.html

Closes #1636 
I have added two features in the H.P.  Calc that calculates sum of first N terms and harmonic Mean.

Added more functionality in Harmonic Progression Calculator

---

assets/contact/contact.html

Closes #1727 
Added a scroll to top button on the Contact Us page, similar to other pages.
https://github.com/user-attachments/assets/b65ddc94-3a98-49fb-bb4d-56ca142e08d4

Added scroll to top button in Contact page

---

Calculators/Luminous-Flux-Calculator/README.md
Calculators/Luminous-Flux-Calculator/index.html
Calculators/Luminous-Flux-Calculator/script.js
Calculators/Luminous-Flux-Calculator/style.css
index.html

Closes #1624 
Added Luminous Flux Calculator that matches the theme of the website as well as calculator.
Made it responsive too.
https://github.com/user-attachments/assets/38e42960-d9aa-4ae5-95c7-0f7a01d62a90

Added Luminous Flux Calculator

---

Calculators/Octal-Calculator/README.md
Calculators/Octal-Calculator/index.html
Calculators/Octal-Calculator/script.js
Calculators/Octal-Calculator/style.css
index.html

Closes #1701 
I have added the octal calculator which performs 4 operations addition, subtraction, division and multiplication on octal numbers.

Added Octal Calculator

---

Calculators/Lottery-Odds-Calculator/README.md
Calculators/Lottery-Odds-Calculator/index.html
Calculators/Lottery-Odds-Calculator/script.js
Calculators/Lottery-Odds-Calculator/style.css
index.html

Closes #1613 
Added the Lottery Odds Calculator

Added Lottery Odds Calculator

---

Calculators/RD-Calculator/README.md
Calculators/RD-Calculator/index.html
Calculators/RD-Calculator/script.js
Calculators/RD-Calculator/style.css
index.html

Closes #1580 
Added RD Calculator.
https://github.com/user-attachments/assets/ad136cd5-b574-4ccb-a666-4208e44c23f4

Added RD Calculator

---

Calculators/Wavelength-Calculator/README.md
Calculators/Wavelength-Calculator/index.html
Calculators/Wavelength-Calculator/script.js
Calculators/Wavelength-Calculator/style.css
index.html

Closes #1563 
Wavelength Calculator: calculates wavelength with the given speed and freq.

Added Wavelength Calculator

---

Calculators/Money-Counter-Calculator/README.md
Calculators/Money-Counter-Calculator/index.html
Calculators/Money-Counter-Calculator/script.js
Calculators/Money-Counter-Calculator/style.css
index.html

Closes #1685 
The Money Counter Calculator allows users to input quantities of various banknotes and coins, calculates the total amount in Indian Rupees (INR), and converts the total into a selected currency.
https://github.com/user-attachments/assets/48a56cc2-7abe-452a-b71c-1177f9a0ec0b

Added Money Counter Calculator

---

style.css

Closes #1796
I've added hover effect on the pagination buttons i.e. 'Previous' and 'Next' matching the UI.

Added hover effect to the pagination buttons

---

Calculators/Sine-Formula-Calculator/README.md
Calculators/Sine-Formula-Calculator/index.html
Calculators/Sine-Formula-Calculator/script.js
Calculators/Sine-Formula-Calculator/style.css
index.html

Closes #1777 
Added Sine-Formula-Calculator

Added Sine Formula Calculator

---

Calculators/Mass-Spring-Calculator/README.md
Calculators/Mass-Spring-Calculator/index.html
Calculators/Mass-Spring-Calculator/script.js
Calculators/Mass-Spring-Calculator/style.css
index.html

Closes #1798 
The Mass-Spring Calculator is a web application that calculates various properties of a mass-spring system. Given the mass of the object (m), the spring constant (k), and the amplitude (A), the calculator computes the following properties:
- Period of Oscillation (T)
- Frequency of Oscillation (f)
- Angular Frequency (ω)
- Maximum Speed (v_max)
- Maximum Acceleration (a_max)
- Kinetic Energy at Maximum Speed (KE)
- Potential Energy at Maximum Displacement (PE)

Added Mass Spring Calculator

---

index.html
script.js

Closes #1888 
Added auto-scroll animation to next and previous button on calculators page.
https://github.com/user-attachments/assets/6719667e-df10-40fb-8fbe-0f044fc8799c

Added auto scroll to top when clicked on pagination buttons

---

style.css

Closes #1897 
In the home page Enhanced the pagination buttons styled of next and previous buttons.

Enhanced the pagination buttons

---

Calculators/Factor-Calculator/README.md
Calculators/Factor-Calculator/index.html
Calculators/Factor-Calculator/script.js
Calculators/Factor-Calculator/style.css
Calculators/Zodiac-Sign-Calculator/index.html
index.html

Closes #1824 
Added a Factor Calculator, which is a simple and interactive web application designed to calculate all the factors of a given number. With a clean and user-friendly interface, it allows users to quickly input a number and view its factors in a visually appealing format.

Added Factor Calculator

---

Calculators/GST-Calculator/script.js

Closes #1852 
In the GST Calculator, fixed the final price in USD.

Fixed the calculation in GST Calculator

---

assets/about/about.html
assets/contact/contact.html
assets/contributors/contributor.html
assets/faq/faq.html
index.html
style.css

Closes #1896 
In this PR, I have updated the footer UI of all the pages.

Enhanced the footer UI

---

assets/contact/contact.css
assets/contact/contact.html

Closes #1894 
This PR introduces dark mode support to the Contact page, improving user experience for those who prefer a dark interface or use the website in low-light environments. It includes a toggle option to switch between light and dark modes and ensures proper color adjustments for all elements.
##In light mode

Added dark mode to Contact page

---

style.css

Closes #1925 
Updated the slider background color in dark mode to better align with the overall dark theme. The previous gray color was inconsistent with the theme and has been replaced with a more suitable dark blue shade for better visual appeal and user experience.

Changed the theme slider background color in dark mode

---

assets/customcursor.css

Closes #1921 
The current cursor color does not suit the dark mode background. A suitable cursor color that complements the dark mode theme is required. Additionally, the cursor color should toggle dynamically between appropriate colors when the theme is altered from dark to light mode and vice versa.

Enhanced the cursor color in dark mode

---

style.css

Closes #1927 
Implemented a more dynamic hover effect that respects the current theme, ensuring that the navbar components change color accordingly—different colors for dark and light modes.

Enhanced the navbar menu items hover effect

---

style.css

Closes #1928 
Developed a dynamic hover effect that adapts to the current theme, ensuring the navbar's logo text change colors appropriately, with distinct shades for dark and light modes.

Enhanced the navbar logo text hover effect

---

assets/commonscript.js
style.css

Closes #1929 
**Enhanced Scroll-to-Top Button**  
- Improved the design and functionality of the scroll-to-top button for both themes.  
- Applied distinct color patterns for light mode and dark mode to provide a visually cohesive and user-friendly experience.  
These updates aim to enhance the overall usability and aesthetics of the scroll-to-top feature across different themes.

Enhanced the scroll to top button for both the themes

---

style.css

Closes #1930 
**Enhanced mic Button**  
- Improved the design and of the mic button for both themes.  
- Applied distinct color patterns for light mode and dark mode to provide a visually cohesive and user-friendly experience.  
These updates aim to enhance the overall usability and aesthetics of the scroll-to-top feature across different themes.
---

Enhanced the mic button color scheme

---

assets/contributors/contributor.css
assets/contributors/contributor.html

Closes #1943 
- Modified the hover color in the CSS/stylesheet for the heading element in the **Contributors** section.
- Ensured the updated hover effect improves accessibility and provides a seamless user experience.

Enhanced the hover color of heading in contributors page

---

Calculators/Love-Calculator/README.md
Calculators/Love-Calculator/index.html
Calculators/Love-Calculator/script.js
Calculators/Love-Calculator/style.css

Closes #1979 
Love Calculator UI updated.

Enhanced the Love Calculator UI

---

404.html
assets/404/404.css
assets/404/404.js
style.css

Closes #1984
I have significantly enhanced the **404 Not Found** page to provide a more engaging and user-friendly experience. The following improvements were made:
- **Interactive Visual Enhancement** 🎨
- Integrated **Particle.js** to create a dynamic and visually appealing background, making the error page feel less frustrating and more immersive.
- **Smart Navigation with Gamification** 🎮
- Introduced a **simple arithmetic challenge** that users must solve to return to the home page, making navigation both engaging and intuitive.
- This adds a fun, interactive element to the error page rather than just displaying a static message.
- On every wrong answer there will be a joke related to 404 and whenever the user correctly handles the answer the GO TO
HOME button would be displayed.
- …

Enhanced the 404 error page
