style.css
Closes Issue #40 
Description👨‍💻 
In the present interface the different calculators are in different size which gives an ODD look for the user.
So as a minor change has been done to resolve this issue.
This give a decent look to the overall project.
The changes made adds up to:
-a good interface to the project
-maintains regularity
#SWOC
The changes made can be seen in the below attached screenshots.
**Before Making Changes:** 
**After Making Changes:**
=> Bug #40 : Equal Size Of Calculators Display

style.css
Closes #107 & #108
Issue #107 
The mail heading "Calcdiverse" font was exceeding the main container making it unresponsive on mobile screen. I have made the changes in overall padding and font size to make it mobile responsive. In addition to that I have updated the media queries as well, so that it doesn't conflict with the real code.
Issue #108 
The "2D Shapes Calculator" card on the mobile screen overlapped the "Explore Calculator" Button. I have made fixes by reducing the padding around the cards div and paragraph div and also added margin to the container in the media screen so that it works normally on all the screens and maintains the responsiveness of the website
I have checked the website after fixes via Chrome developer tools making various checks with all types of screens …
=> Fixed Issue #107 and Issue #108

Calculators/Length-Calculator/Length.html, Calculators/Length-Calculator/Length.js
Closes #340 
I added new measures in the [Length Calculator](https://calcdiverse.netlify.app/calculators/length-calculator/length):
- Hectometre
- Decametre
- Decimetre
I added new options with those measures for both "unitFrom" and "unitTo" in the html code. 
```
<select id="unitTo">
<option value="km">Kilometers</option>
<option value="hm">Hectometers</option> NEW 
<option value="dam">Decameters</option> NEW 
<option value="m" selected>Meters</option>
<option value="dm">Decimeters</option> NEW 
<option value="cm">Centimeters</option>
<option value="mm">Millimeters</option>
</select>
Same goes for the unitFrom tag.
```
And for this to work I added the conversion factors for hm , dam and dm.
```
let conversionFactors = {
km: 1000,
hm: 100,
dam: 10,
m: 1,
dm: 0.1,
cm: 0.01, 
mm: 0.001,
}; …
```
=> [Feature] Added new measures in the length calculator

assets/contributors/contributor.css
Closes #421 
I have fixed the contributor.css file code and made the font family same for both the pages Navbar elements.
=> Made home and contributor page font family consistent

Calculators/Age-Calculator/Age-Calculator.html
Closes #468 
There was a spelling error in the page title of the age calculator page. This has been replaced with the correct spelling.
The page title is named with the correctly spelled word
=> Spelling fixed in Age Calculator Title

Calculators/Age-Calculator/Age-Calculator.css, Calculators/Age-Calculator/Age-Calculator.html, Calculators/Age-Calculator/Age-Calculator.js
Closes #569 
1. Added animation styles to Age Calculator title.
2. Set a default valid age to avoid any errors in the first go.
3. Added custom alerts
4. Added alerts for negative age too.
5. Added shadows and hover styling to main container for age calculator
6. Added a favicon for Age Calculator page
Edge Web Browser and Chrome Browser on local machine.
=> Added styling and custom alert to Age Calculator

Calculators/Neon-Number-Calculator/README.md, Calculators/Neon-Number-Calculator/index.html, Calculators/Neon-Number-Calculator/script.js, Calculators/Neon-Number-Calculator/style.css, index.html
Closes #520 
Added new calculator to check and find neon number in range.
=> Added Neon Number Calculator

.vscode/settings.json, Calculators/Circular-Prime-Calculator/README.md, Calculators/Circular-Prime-Calculator/index.html, Calculators/Circular-Prime-Calculator/script.js, Calculators/Circular-Prime-Calculator/style.css, index.html
Closes #521 
Added Circular Prime Calculator
=> Added Circular Prime Calculator

Calculators/Percentage-Calculator/index.html, Calculators/Percentage-Calculator/script.js, Calculators/Percentage-Calculator/style.css
Closes #541 
Changed the UI and UX of percentage calculator page.
Works on live server and ran locally on server.
=> Enhanced Percentage Calculator UI

Calculators/Yarn-Density-Calculator/README.md, Calculators/Yarn-Density-Calculator/index.html, Calculators/Yarn-Density-Calculator/script.js, Calculators/Yarn-Density-Calculator/style.css, index.html
Closes #601 
The Yarn Density Calculator is a web-based tool designed to assist users in computing conversion of different unit values based on input parameters related to a material's unit required. 
I have tested it locally
=> Added Yarn Density Calculator

Calculators/Happy-Number-Calculator/README.md, Calculators/Happy-Number-Calculator/index.html, Calculators/Happy-Number-Calculator/script.js, Calculators/Happy-Number-Calculator/style.css, index.html
Closes #605 
Added Happy Number Calculator.
=> Added Happy Number Calculator

Calculators/Palindrome-Calculator/README.md, Calculators/Palindrome-Calculator/index.html, Calculators/Palindrome-Calculator/script.js, Calculators/Palindrome-Calculator/styles.css, index.html
Closes #558 
Inputs string or a number from the user, and returns whether it is a palindrome or not.
Tested with various number of inputs
=> Added Palindrome Calculator

Calculators/Armstrong-Number-Calculator/index.html
Closes #655 
The html code </label> was being displayed on the website which is fixed now.
=> Fixed the displayed html tag in Armstrong Number Calculator

Calculators/Logarithm-Calculator/index.html, Calculators/Logarithm-Calculator/script.js, Calculators/Logarithm-Calculator/style.css
Closes #630 
The base input while calculating the log should be positive and not 1. This issue has been fixed by inculcating the necessary changes in index.html file in the input tag and using validateBaseInput function.
Also the number whose log is being calculated should be positive which has been fixed on the similar lines by making changes in the input tag.
For more detailed information, review the changes made section.
```javascript
function validateBaseInput(base) {
const errorElement = document.getElementById('baseError');
if (base.value == 1) {
errorElement.style.display = 'inline';
} else {
errorElement.style.display = 'none';
}
}
``` 
Tested on my PC locally by entering the inputs that resulted in bug such as:-
The screenshot has been attached for the same which showcases that …
=> Fixed negative inputs in Logarithmic Calculator

index.html
Closes #668 
I have noticed that the source code is available when I click on it.
So it's really the page not found.
So I checked the route/path which is responsible to load currency calculator.
So, I have fixed the path and now it's properly working.
https://github.com/Rakesh9100/CalcDiverse/assets/112798996/26e6a5c3-f990-4bc0-bd21-38dbce4bce0b
The above shows the proper working of the site.
=> Fixed the link to open Currency Calculator

Calculators/Recipe-Cost-Calculator/README.md, Calculators/Recipe-Cost-Calculator/index.html, Calculators/Recipe-Cost-Calculator/script.js, Calculators/Recipe-Cost-Calculator/style.css, index.html
Closes #670  
Enables users to input ingredients and quantities to calculate the total cost of a recipe, facilitating budget-friendly meal planning.
=> Added Recipe Cost Calculator

Calculators/Days-Until-Deadline-Calculator/README.md, Calculators/Days-Until-Deadline-Calculator/index.html, Calculators/Days-Until-Deadline-Calculator/script.js, Calculators/Days-Until-Deadline-Calculator/style.css, index.html
Closes #557 
This pull request adds a new feature to the website: a "Days Until Deadline Calculator." The calculator allows users to select a date and calculates the number of days remaining until that date. This includes the following changes:
- A user-friendly interface with a date input field and a calculate button.
- A visually appealing background gradient for the webpage.
- A semi-transparent container with a subtle pattern for better readability and aesthetics.
No additional dependencies are required for this change.
This feature has been tested by:
- Manually selecting different dates and verifying that the correct number of days remaining is displayed.
- Ensuring the gradient background and patterned container render correctly on various screen sizes.
- Checking the readability …
=> Added Days Until Deadline Calculator

Calculators/Pet-Age-Calculator/README.md, Calculators/Pet-Age-Calculator/index.html, Calculators/Pet-Age-Calculator/script.js, Calculators/Pet-Age-Calculator/style.css, index.html
Closes #698 
Added a new calculator name the Pet-Age-Calculator that adds a calculator that calculates a pets age in human years
Tested on various values for years and months for different pets
=> Added Pet Age Calculator

Calculators/Book-Reading-Time-Calculator/style.css
Closes #800 
made changes in css
=> Made Book Reading Time Calculator responsive

Calculators/Roman-Numeral-Calculator/README.md, Calculators/Roman-Numeral-Calculator/index.html, Calculators/Roman-Numeral-Calculator/script.js, Calculators/Roman-Numeral-Calculator/style.css, index.html
Closes #810 
Added a new folder called Roman-Numeral-Calculator in the Calculators folder 
Added a new box linking to my calculator in the index.html file.
Tested on all the values within range.
=> Added Roman Numeral Calculator

Calculators/CGPA-Percentage-Calculator/README.md, Calculators/CGPA-Percentage-Calculator/script.js
Closes #819 
I have corrected the formulas in CGPA Percentage Calculator and also updated the readme file for the same.
I have tested it by giving many inputs in the columns of CGPA and percentage both, and now it is functioning well.
=> Corrected the calculation in CGPA Percentage Calculator

assets/contact/contact.js
Closes #872 
In the contact us form, a check over message length has been applied such that length of message should be at least 50 chars.
It'll help to avoid receiving empty 1-2 character messages which others may send without any purpose.
This may help in decluttering the message piles being received.
Tested locally on my system. Screenshot for the same has been attached.
=> Implemented length constraint for message in Contact Us form

Calculators/Retirement-Calculator/README.md, Calculators/Retirement-Calculator/index.html, Calculators/Retirement-Calculator/script.js, Calculators/Retirement-Calculator/style.css, index.html
Closes #822 
This pull request adds a new feature to the website: a "Retirement Calculator". The Calculator predicts users' retirement savings growth by factoring in age, savings, contributions, and expected returns, facilitating informed financial planning for a comfortable retirement. This includes the following changes:
- Simple and minimalistic code with easy-understanding logic.
- A user-friendly interface with a date input field and a calculate button.
- A visually appealing background gradient for the webpage with animation.
- A semi-transparent container with a subtle pattern for better readability and aesthetics.
No additional dependencies are required for this change.
This feature has been tested by:
- Manually providing different inputs and verifying that the Estimated Output …
=> Added Retirement Calculator

.vscode/settings.json, style.css
Closes #887
Changed the color of logo text CalcDiverse in the navbar on the main page to make the color on whole navbar similar.
Tested locally on my PC. Screenshot of the same has been attached.!
=> Made the color of logo text same on hover

Calculators/Sleep-Cycle-Calculator/README.md, Calculators/Sleep-Cycle-Calculator/index.html, Calculators/Sleep-Cycle-Calculator/script.js, Calculators/Sleep-Cycle-Calculator/style.css, index.html
Closes #946 
The sleep cycle calculator calculates optimal bedtimes based on desired wake-up time and the scientific 90-min sleep cycles.
Tested on various wake up timings to ensure the accuracy of results.
=> Added Sleep Cycle Calculator

assets/contributors/contributor.js
Closes #996 
Now API limited increased to 5000 pr hr.
Tested on my local machine.
=> Fixed the API request on fetching contributors

Calculators/Solar-Power-Saving-Calculator/README.md, Calculators/Solar-Power-Saving-Calculator/Readme.md, Calculators/Solar-Power-Saving-Calculator/index.html, Calculators/Solar-Power-Saving-Calculator/script.js, Calculators/Solar-Power-Saving-Calculator/style.css, index.html
Closes #1050 
The user needs to choose a state where they want to install the solar panels. Depending on that, it automatically fetches Installation cost and incentives and rebate for that state. The user also needs to enter information like roof area, tilt, electricity consumption per month and preferred solar system size. 
=> Added Solar Power Saving Calculator

Calculators/Euclidean-Algorithm-Calculator/README.md, Calculators/Euclidean-Algorithm-Calculator/index.html, Calculators/Euclidean-Algorithm-Calculator/script.js, Calculators/Euclidean-Algorithm-Calculator/style.css, index.html
Closes #1080 
This pull request adds a new feature to the website: a "Euclidean Algorithm Calculator." The calculator allows users to compute the Greatest Common Divisor (GCD) and the Least Common Multiple (LCM) of two integers entered.
This includes the following changes:
- A user-friendly interface with the "two required numbers" input field and a calculate button.
- A visually appealing dark-themed background for the webpage.
No additional dependencies are required for this change.
This feature has been tested by:
- Manually giving several inputs and verifying that the correct GCD and LCM are displayed.
- Ensuring the gradient "calculate" button and the container render correctly on various screen sizes.
- Checking the readability of text within the container against the dark-themed …
=> Added Euclidean Algorithm Calculator

Calculators/Marks-Percentage-Calculator/README.md, Calculators/Marks-Percentage-Calculator/index.html, Calculators/Marks-Percentage-Calculator/script.js, Calculators/Marks-Percentage-Calculator/style.css, index.html
Closes #967 
A Marks to Percentage Calculator is a tool designed to convert the marks obtained in various subjects into a percentage. 
It allows users to input the number of subjects and the marks obtained in each subject. 
The calculator then sums up the total marks and computes the average percentage based on the number of subjects. 
Self run after all changes in code.
=> Added Marks Percentage Calculator

assets/about/about.css, assets/about/about.html, assets/contact/contact.css, assets/contact/contact.html, assets/contributors/contributor.css, assets/contributors/contributor.html, assets/faq/faq.css, assets/faq/faq.html, index.html, style.css
Closes #1318 
On the website there is no LinkedIn profile, It is added to all the pages of the website.
@Rakesh9100, I kindly request you to review the changes and merge them to contribute to the project, sir.
Thank you sir
=> Added LinkedIn icon in footer

Calculators/T-Score-Calculator/README.md, Calculators/T-Score-Calculator/index.html, Calculators/T-Score-Calculator/script.js, Calculators/T-Score-Calculator/style.css, index.html
Closes #1446 
I have added T-Score calculator
Added the theme of statistic to match the calculator as well as the theme of the website.
https://github.com/Rakesh9100/CalcDiverse/assets/168854094/b434364e-842d-44d6-a953-090fe26aca90
=> Added T-Score Calculator

style.css
Closes #1042 
Modified media queries to enhance navbar from 769 to 1060 width. The distorted lines arise due to the display of contents in 2 lines, as it couldn't fit. So changed the font-size and padding of the navbar items to fit the items in a single line.
=> Made the navbar responsive

Calculators/Plant-Care-Calculator/README.md, Calculators/Plant-Care-Calculator/index.html, Calculators/Plant-Care-Calculator/script.js, Calculators/Plant-Care-Calculator/style.css, index.html
Closes #1607 
This calculator calculates schedule for aspects like watering, fertilizing and repotting plants based upon the plant size, season, location and water frequency.
https://github.com/user-attachments/assets/ec857c9f-6006-48b5-86fa-dd9ecc1a8791
=> Added Plant Care Calculator

Calculators/Atomic-Composition-Calculator/README.md, Calculators/Atomic-Composition-Calculator/index.html, Calculators/Atomic-Composition-Calculator/script.js, Calculators/Atomic-Composition-Calculator/style.css, index.html
Closes #712 
The calculator determines the number of protons, neutrons, and electrons in an atom based on its atomic number, atomic mass, and charge. It supports both neutral atoms and ions.
I have also handled the error validation.
=> Added Atomic Composition Calculator

Calculators/Numerology-Calculator/README.md, Calculators/Numerology-Calculator/index.html, Calculators/Numerology-Calculator/script.js, Calculators/Numerology-Calculator/style.css, Calculators/Numerology-Calculator/styles.css, index.html
Closes #1587 
Discover your core numerology numbers and insights into personality, life purpose, and future outcomes.
=> Added Numerology Calculator

assets/about/about.html, assets/contact/contact.html, assets/contributors/contributor.html, assets/contributors/contributor.js, assets/faq/faq.html, index.html, script.js, style.css
Closes #1597 
I have added a progress bar on the top of the navbar which progresses as the page scrolls up or down.
https://github.com/user-attachments/assets/5e3ee77e-213e-40d2-8b8b-3c3eddd9b921
=> Added scroll progress indicator bar

Calculators/Body-Shape-Calculator/README.md, Calculators/Body-Shape-Calculator/index.html, Calculators/Body-Shape-Calculator/script.js, Calculators/Body-Shape-Calculator/style.css, Calculators/Clothing-Size-Calculator/index.html, index.html
Closes #1686 
This new body shape calculator feature helps you determine your body type by comparing your waist, bust/chest, and hip measurements to categorize you as a rectangle, hourglass, triangle, or another shape. It will then suggest styling ideas for clothes based on your body shape.
=> Added Body Shape Calculator

Calculators/Unit-Calculator/index.html, Calculators/Unit-Calculator/script.js, Calculators/Work-Calculator/index.html, Calculators/Work-Calculator/script.js, Calculators/Work-Calculator/style.css
Closes #1632 
- **HTML**
- Added a new dropdown menu in the form for unit conversion with the following options: Joule (J), ElectronVolt (eV), Calorie (cal), Kilocalorie (kcal), Foot-pound (ft-lb), and Kilowatt-hour (kWh).
- **JS**
- Added logic for conversion of unit for Work using International standards of conversion, with concise and efficient code.
These changes were made to provide users with the ability to convert the work value into various units of energy. 
- Verified that the dropdown menu appears correctly with the specified units.
- Ensured that the dropdown styling is applied correctly and the box size is increased.
Please review the changes and let me know if any adjustments are needed.
=> Added Work unit conversion in Unit Calculator

Calculators/Fraction-Calculator/README.md, Calculators/Fraction-Calculator/index.html, Calculators/Fraction-Calculator/script.js, Calculators/Fraction-Calculator/style.css
Closes #1467 
Here is a summary of the changes made to the Fraction Calculator project:
1.  HTML Update :
- Added a new input field in the form to display the decimal result.
2.  JavaScript Update :
- Updated the `solve` function to calculate and display the decimal equivalent of the resulting fraction.
- Included a check in the `display` function to alert if the result is not a real number.
3.  CSS Update :
- Styled the new input field for the decimal result to match the existing input fields.
4.  README Update :
- Updated the project description to include the new functionality of converting fractions to decimals and checking if the result is a real number.
- Added detailed instructions on how to use the updated features.
=> Added more functionality in Fraction Calculator

Calculators/Arithmetic-Progression-Calculator/README.md, Calculators/Arithmetic-Progression-Calculator/index.html, Calculators/Arithmetic-Progression-Calculator/script.js, index.html
Closes #1770 
I have added an option to calculate the arithmetic mean in the Arithmetic Progression Calculator
=> Added mean functionality in Arithmetic Progression Calculator

Calculators/Restaurant-Planning-Calculator/README.md, Calculators/Restaurant-Planning-Calculator/index.html, Calculators/Restaurant-Planning-Calculator/scripts.js, Calculators/Restaurant-Planning-Calculator/styles.css, index.html
Closes #1788 
This Restaurant Planning Calculator helps users efficiently plan their restaurant by calculating the initial and monthly costs based on various inputs such as available space, number of staff, rent, utilities, equipment costs, and salaries. It provides detailed insights on cost management, space optimization, and budget planning. The intuitive interface ensures easy input and clear results, aiding in effective financial planning and resource management for restaurant owners.
=> Added Restaurant Planning Calculator

Calculators/Pythagorean-Theorem-Calculator/script.js
Closes #1811 
This pull request addresses the bug where the hypotenuse was incorrectly calculated when one of the sides was entered as zero. The updated implementation now correctly handles this case.
=> Fixed the zero calculation in Pythagorean Theorem Calculator

Calculators/Decimal-Roman-Calculator/README.md, Calculators/Decimal-Roman-Calculator/index.html, Calculators/Decimal-Roman-Calculator/script.js, Calculators/Decimal-Roman-Calculator/styles.css, index.html
Closes #1757 
Added a decimal roman calculator which changes given decimal number to roman number and vice-versa.
=> Added Decimal Roman Calculator

Calculators/Electric-Vehicle-Savings-Calculator/index.html, Calculators/Electric-Vehicle-Savings-Calculator/script.js, Calculators/Electric-Vehicle-Savings-Calculator/styles.css, Calculators/README.md, index.html
Closes #1723 
Added a new calculator that calculates the cost of a gasoline vehicle per/km and a electric vehicle calculator.
=> Added Electric Vehicle Savings Calculator

Calculators/BMI-Calculator/index.html, Calculators/BMI-Calculator/script.js, Calculators/BMI-Calculator/style.css, Calculators/Binary-Calculator/index.html, Calculators/Binary-Calculator/script.js, Calculators/Binary-Calculator/style.css, Calculators/Tangent-Formula-Calculator/README.md, Calculators/Tangent-Formula-Calculator/index.html, Calculators/Tangent-Formula-Calculator/script.js, Calculators/Tangent-Formula-Calculator/style.css, index.html
Closes #1861 
Closes #1862 
1. This PR enhances the functionality of the convertFeetToCm function by adding support for feet input. Previously, the function only accepted centimeter (cm) values, limiting its flexibility. With this update, users can now input a value in feet, and the function will convert it to total centimeters.
2. The requirement is to integrate a new calculator into the existing project. The tan calculator should allow users to input a value (angle) and calculate its tangent.
3. Changes in Binary Calculator
Added Decimal Output:
A new parameter p has been introduced that allows the results to be displayed in decimal format in addition to binary. This enhances usability by providing users with a more familiar numerical representation.
Implemented Division Method: …
=> Added Tangent Formula Calculator and Height Unit option in BMI Calculator

assets/faq/faq.css, assets/faq/faq.html
Closes #1892 
This PR introduces dark mode support to the FAQ page. Dark mode enhances the user experience for those who prefer a dark interface or access the website in low-light environments. By providing a dark mode option, this update improves accessibility and aligns the FAQ page with modern UI standards.
=> Added dark mode to FAQ page

style.css
Closes #1887 
This PR addresses the issue of the outdated and simplistic design of the Google Translate dropdown on the CalcDiverse website. The dropdown currently lacks modern, visually appealing design elements, which affects the overall user experience. This update aims to improve the dropdown's style to make it more user-friendly and cohesive with the website's design language.
> A dynamic linear gradient background featuring the colors of Google (blue, red, yellow, and green) has been added, creating a vibrant and engaging visual experience. This gradient moves smoothly, adding a modern touch.
=> Enhanced the google translate dropdown

assets/faq/faq.css, assets/faq/faq.html, assets/faq/faq.js
Closes #1297 
This PR aims to correctly style the accordion in FAQ's page. 
[watch video](https://github.com/user-attachments/assets/1750ac21-aa7c-446e-a127-0798dffb8a7a)
=> Fixed the accordion in FAQ page

Calculators/Infix-Prefix-Postfix-Calculator/index.html, Calculators/Infix-Prefix-Postfix-Calculator/script.js, Calculators/Infix-Prefix-Postfix-Calculator/style.css
Closes #1236 
Added table for infix-prefix-postfix conversion calculator. For better user experience and understanding.  
[video](https://github.com/user-attachments/assets/ecd43684-11d8-4ed7-9147-292f7c9ad97d)
=> Added stack representation in Infix Prefix Postfix Calculator

assets/about/about.html, assets/contact/contact.html, assets/contributors/contributor.html, assets/faq/faq.html, index.html, style.css
Closes #1916 
This PR moves the theme toggle button next to the hamburger icon on small screens for better accessibility. Previously, the toggle was hidden inside the hamburger menu, making it harder to access. The layout has been adjusted using CSS to align both elements side by side, ensuring a more user-friendly experience on mobile devices.
Repositioned theme toggle next to the hamburger icon on small screens.
Adjusted CSS for better alignment and responsiveness.
Improved the visibility and accessibility of the theme toggle on small screens.
=> Fixed the theme button position on small devices

style.css
Closes #1933 
This pull request addresses two key issues with the guiding buttons in CalcDiverse:
1. **Dynamic Hover Effect with Theme Change**: The hover effect of the guiding buttons (`Next` and `Previous`) is not currently dynamic when switching between the light and dark themes. This update ensures that the hover effect adapts properly to the selected theme.
2. **Modernized Button Styling**: The styling of the buttons has been improved to align with modern design standards, making them more visually appealing.
<br>
=> Enhanced the pagination buttons according to the theme

Calculators/Ballistic-Coefficient-Calculator/README.md, Calculators/Ballistic-Coefficient-Calculator/index.html, Calculators/Ballistic-Coefficient-Calculator/script.js, Calculators/Ballistic-Coefficient-Calculator/style.css, calculators.json
Closes #1856 
Added Ballistic Coefficient Calculator.
Ballistic coefficient calculator is a tool used in ballistics to determine the ballistic coefficient of a projectile, such as a bullet. The ballistic coefficient is a measure of a projectile's ability to overcome air resistance during flight. It is an essential factor in understanding how a projectile will behave over long distances, including its trajectory, velocity, and the degree of wind drift.
=> Added Ballistic Coefficient Calculator

Calculators/Weather-Calculator/script.js
Closes #1969 
Added a popup functionality to handle cases where no input is provided, replacing `NaN` outputs with a user-friendly alert message prompting input.
---
Please assign under SWOC '25...
=> Handled NaN validation in Weather Calculator
